### ISSUE TITLE
Support additional modern password-hashing methods SHA256/512

### ISSUE THREAD

**Issue by jkrenzer** [mlan/docker-openldap#3]
Hi!

I wanded to ask if it would be possible to install the additional apk-package "openldap-passwd-sha2" in the Dockerfile. This way, openldap can support SHA256 + SHA512 hashes and their salted variants for passwords.

Thanks!

Jörn

**Comment by mlan** [comment]
@jkrenzer 

Did you make the pull request to the main repo?

**Comment by jkrenzer** [comment]
Yes. I did monkey-patch it for myself so i figured I could as well offer the edit directly.

**Comment by mlan** [comment]
@jkrenzer

You are welcome to place a pull request against the repo if you desire.

**Comment by mlan** [comment]
This issue was resolved in ec5a7fd5551cd37e5884368ea0d564772d60925f.
